import checkoutFormModel from './settingsCheckoutFormModel';

const {
  formField: {
    workLocation,
    assetType,
    poReference,
    partsRequired,
    preparedRequired,
    ehsRequired,
    reviewRequired,
    nightShiftFrom,
    nightShiftTo,
    nightApproval,
    nightStart,
    nightEnd,
    nightStartMax,
    nightEndMax,
    nightTitle,
    nightWorkType,
    specialShiftFrom,
    specialShiftTo,
    specialApproval,
    specialStart,
    specialEnd,
    specialStartMax,
    specialEndMax,
    specialTitle,
    specialWorkType,
    generalShiftFrom,
    generalShiftTo,
    generalApproval,
    generalStart,
    generalEnd,
    generalStartMax,
    generalEndMax,
    generalTitle,
    generalWorkType,
    createMessage,
    createAuthorize,
    authorizeMessage,
    authorizeApprover,
    authorizeEHS,
    authorizeVendor,
    authorizeRequestor,
    prepareMessage,
    prepareApprover,
    prepareRequestor,
    prepareEHS,
    permitMessage,
    permitApprover,
    permitEHS,
    permitVendor,
    permitRequestor,
    permitSecurity,
    ehsMessage,
    ehsApprover,
    ehsEHS,
    ehsVendor,
    ehsRequestor,
    ehsSecurity,
    orderMessage,
    orderReview,
    orderApprover,
    closeMessage,
    closeApprover,
    closeEHS,
    closeVendor,
    closeRequestor,
    closeSecurity,
    withinDay,
    rButton,
    aButton,
    pButton,
    iButton,
    vButton,
    wButton,
    oButton,
    clButton,
    prButton,
    eButton,
    cButton,
    rStatus,
    aStatus,
    pStatus,
    iStatus,
    vStatus,
    wStatus,
    oStatus,
    clStatus,
    prStatus,
    eStatus,
    cStatus,
    actualStart,
    actualEnd,
    enableType,
    workAccess,
    enableDepartment,
    departmentAccess,
  },
} = checkoutFormModel;

export default {
  [workLocation.name]: '',
  [assetType.name]: '',
  [poReference.name]: '',
  [partsRequired.name]: '',
  [preparedRequired.name]: '',
  [ehsRequired.name]: '',
  [reviewRequired.name]: '',
  [nightShiftFrom.name]: '',
  [nightShiftTo.name]: '',
  [nightApproval.name]: '',
  [nightStart.name]: '',
  [nightEnd.name]: '',
  [nightStartMax.name]: '',
  [nightEndMax.name]: '',
  [nightTitle.name]: '',
  [nightWorkType.name]: '',
  [specialShiftFrom.name]: '',
  [specialShiftTo.name]: '',
  [specialApproval.name]: '',
  [specialStart.name]: '',
  [specialEnd.name]: '',
  [specialStartMax.name]: '',
  [specialEndMax.name]: '',
  [specialTitle.name]: '',
  [specialWorkType.name]: '',
  [generalShiftFrom.name]: '',
  [generalShiftTo.name]: '',
  [generalApproval.name]: '',
  [generalStart.name]: '',
  [generalEnd.name]: '',
  [generalStartMax.name]: '',
  [generalEndMax.name]: '',
  [generalTitle.name]: '',
  [generalWorkType.name]: '',
  [createMessage.name]: '',
  [createAuthorize.name]: '',
  [authorizeMessage.name]: '',
  [authorizeApprover.name]: '',
  [authorizeEHS.name]: '',
  [authorizeVendor.name]: '',
  [authorizeRequestor.name]: '',
  [prepareMessage.name]: '',
  [prepareApprover.name]: '',
  [prepareRequestor.name]: '',
  [prepareEHS.name]: '',
  [permitMessage.name]: '',
  [permitApprover.name]: '',
  [permitEHS.name]: '',
  [permitVendor.name]: '',
  [permitRequestor.name]: '',
  [permitSecurity.name]: '',
  [ehsMessage.name]: '',
  [ehsApprover.name]: '',
  [ehsEHS.name]: '',
  [ehsVendor.name]: '',
  [ehsRequestor.name]: '',
  [ehsSecurity.name]: '',
  [orderMessage.name]: '',
  [orderReview.name]: '',
  [orderApprover.name]: '',
  [closeMessage.name]: '',
  [closeApprover.name]: '',
  [closeEHS.name]: '',
  [closeVendor.name]: '',
  [closeRequestor.name]: '',
  [closeSecurity.name]: '',
  [withinDay.name]: '',
  [rStatus.name]: '',
  [aStatus.name]: '',
  [pStatus.name]: '',
  [iStatus.name]: '',
  [vStatus.name]: '',
  [wStatus.name]: '',
  [oStatus.name]: '',
  [clStatus.name]: '',
  [prStatus.name]: '',
  [eStatus.name]: '',
  [cStatus.name]: '',
  [rButton.name]: '',
  [aButton.name]: '',
  [pButton.name]: '',
  [iButton.name]: '',
  [vButton.name]: '',
  [wButton.name]: '',
  [oButton.name]: '',
  [clButton.name]: '',
  [prButton.name]: '',
  [eButton.name]: '',
  [cButton.name]: '',
  [actualStart.name]: '',
  [actualEnd.name]: '',
  [enableType.name]: '',
  [workAccess.name]: '',
  [enableDepartment.name]: '',
  [departmentAccess.name]: '',
};
