import checkoutFormModel from './settingsCheckoutFormModel';

const {
  formField: {
    visitorEmail,
    visitorMobile,
    visitorCompany,
    visitorType,
    visitorPurpose,
    visitorPhoto,
    visitorIP,
    visitorIPNumber,
    idDetails,
    visitorBadge,
    hostCompany,
    hostEmail,
    hostName,
    smsOTP,
    emailOTP,
    whatsappOTP,
    emailInvitation,
    smsInvitation,
    whatsappInvitation,
    enableHostEmail,
    hostDisclaimer,
    enableScreen,
    checklistScreen,
    periodScreen,
    surveyScreen,
    buttonScreen,
    emailScreen,
    allowSites,
    approvalHost,
    allowedDomains,
    closeVisit,
    externalURL,
    visitorAsset,
    enableTerms,
    addTerms,
    createdMessage,
    checkoutFeedback,
    surveyFeedback,
    buttonFeedback,
    emailFeedback,
    emailRequest,
    smsRequest,
    whatsappRequest,
    emailCheckIn,
    smsCheckIn,
    whatsappCheckIn,
    qrCheckIn,
    otpCheckIn,
    gracePeriodCheckIn,
    emailCheckOut,
    smsCheckOut,
    whatsappCheckOut,
    emailApproval,
    smsApproval,
    whatsappApproval,
    emailElapsed,
    smsElapsed,
    whatsappElapsed,
    galleryImage,
    visitorInvitationTemplateId,
    otpTemplateId,
    requestTemplateId,
    checkInTemplateId,
    checkOutTemplateId,
    approvalTemplateId,
    elapsedTemplateId,
    visitorTypes,
    allowedAssetType,
    passHeader,
  },
} = checkoutFormModel;

export default {
  [visitorEmail.name]: '',
  [visitorMobile.name]: '',
  [visitorCompany.name]: '',
  [visitorType.name]: '',
  [visitorPurpose.name]: '',
  [visitorPhoto.name]: '',
  [visitorIP.name]: '',
  [visitorIPNumber.name]: '',
  [idDetails.name]: '',
  [visitorBadge.name]: '',
  [hostCompany.name]: '',
  [hostEmail.name]: '',
  [hostName.name]: '',
  [smsOTP.name]: '',
  [emailOTP.name]: '',
  [whatsappOTP.name]: '',
  [emailInvitation.name]: '',
  [smsInvitation.name]: '',
  [whatsappInvitation.name]: '',
  [enableHostEmail.name]: '',
  [hostDisclaimer.name]: '',
  [enableScreen.name]: '',
  [checklistScreen.name]: '',
  [periodScreen.name]: '',
  [surveyScreen.name]: '',
  [buttonScreen.name]: '',
  [emailScreen.name]: '',
  [allowSites.name]: '',
  [approvalHost.name]: '',
  [allowedDomains.name]: '',
  [closeVisit.name]: '',
  [externalURL.name]: '',
  [visitorAsset.name]: '',
  [enableTerms.name]: '',
  [addTerms.name]: '',
  [createdMessage.name]: '',
  [checkoutFeedback.name]: '',
  [surveyFeedback.name]: '',
  [buttonFeedback.name]: '',
  [emailFeedback.name]: '',
  [emailRequest.name]: '',
  [smsRequest.name]: '',
  [whatsappRequest.name]: '',
  [emailCheckIn.name]: '',
  [smsCheckIn.name]: '',
  [whatsappCheckIn.name]: '',
  [qrCheckIn.name]: '',
  [otpCheckIn.name]: '',
  [gracePeriodCheckIn.name]: '60.00',
  [emailCheckOut.name]: '',
  [smsCheckOut.name]: '',
  [whatsappCheckOut.name]: '',
  [emailApproval.name]: '',
  [smsApproval.name]: '',
  [whatsappApproval.name]: '',
  [emailElapsed.name]: '',
  [smsElapsed.name]: '',
  [whatsappElapsed.name]: '',
  [galleryImage.name]: '',
  [visitorInvitationTemplateId.name]: '',
  [otpTemplateId.name]: '',
  [requestTemplateId.name]: '',
  [checkInTemplateId.name]: '',
  [checkOutTemplateId.name]: '',
  [approvalTemplateId.name]: '',
  [elapsedTemplateId.name]: '',
  [visitorTypes.name]: '',
  [allowedAssetType.name]: '',
  [passHeader.name]: '',
};
