import optFormModel from './optFormModel';

const {
  formField: {
    name,
    sequenceId,
    warehouseId,
    operationType,
    showOperations,
    showReserved,
    isApprovalRequired,
    role,
    isRequestExpiry,
    expiryDuration,
    isExpiryEmail,
    isReminderEmail,
    ReminderDuration,
    Requested,
    Approved,
    Rejected,
    Delivered,
    bnRequested,
    bnApproved,
    bnRejected,
    bnDelivered,
  },
} = optFormModel;

export default {
  [name.name]: '',
  [sequenceId.name]: '',
  [warehouseId.name]: '',
  [operationType.name]: '',
  [showOperations.name]: false,
  [showReserved.name]: true,
  [isApprovalRequired.name]: '',
  [role.name]: '',
  [isRequestExpiry.name]: '',
  [expiryDuration.name]: '',
  [isExpiryEmail.name]: '',
  [isReminderEmail.name]: '',
  [ReminderDuration.name]: '',
  [Requested.name]: 'Requested',
  [Approved.name]: 'Approved',
  [Rejected.name]: 'Rejected',
  [Delivered.name]: 'Delivered',
  [bnRequested.name]: 'Request',
  [bnApproved.name]: 'Approve',
  [bnRejected.name]: 'Reject',
  [bnDelivered.name]: 'Deliver',
};
