import checkoutFormModel from './checkoutFormModel';

const {
  formField: {
    name,
    complianceTemplate,
    complianceCategory,
    complianceAct,
    submittedTo,
    appliesTo,
    location,
    companyId,
    assetIds,
    responsible,
    hasExpiry,
    nextExpiryDate,
    expirySchedule,
    expiryScheduleType,
    repeatUntil,
    endDate,
    renewalLeadTime,
    licenseNumber,
    description,
    Type,
    siteId,
  },
} = checkoutFormModel;

export default {
  [name.name]: '',
  [complianceTemplate.name]: '',
  [complianceCategory.name]: '',
  [complianceAct.name]: '',
  [submittedTo.name]: '',
  [appliesTo.name]: { value: 'Site', label: 'Site(s)' },
  [location.name]: [],
  [companyId.name]: [],
  [assetIds.name]: [],
  [responsible.name]: '',
  [hasExpiry.name]: false,
  [nextExpiryDate.name]: '',
  [expirySchedule.name]: 1,
  [expiryScheduleType.name]: '',
  [repeatUntil.name]: { value: 'Never Ends', label: 'Never Ends' },
  [endDate.name]: '',
  [renewalLeadTime.name]: '',
  [licenseNumber.name]: '',
  [description.name]: '',
  [Type.name]: '',
  [siteId.name]: '',
  url_link: '',
};
