
import { env } from '../../../env';

const ConfigData = {
  WEBAPIURL: env.REACT_APP_WEBAPIURL || 'http://localhost:3000',
  VERSION: env.REACT_APP_VERSION || 'v4/',
  IS_USE_APIGATEWAY: env.REACT_APP_IS_USE_APIGATEWAY || false,
  GOOGLEAPIKEY: env.REACT_APP_GOOGLE_API_KEY || 'AIzaSyCZP-bkwcoGJj9KLsAU10VgodNr5teA_X4',
  GOOGLECAPTCHASITEKEY: env.REACT_APP_GOOGLE_CAPTCHA_SITE_KEY || '6LfzYzUfAAAAADFX4l4BMj2hzXVxf30aPXoTaoQP',
  GOOGLECAPTCHASECRETKEY: env.REACT_APP_GOOGLE_CAPTCHA_SECRET_KEY || '6LfzYzUfAAAAADQ_aoQLU8_8NRaCsIY5kQj876Gq',
  CLIENTNAME: env.REACT_APP_CLIENT_NAME,
  POWERBI_EXPIRY: env.REACT_APP_POWERBI_EXPIRY || 3500000,
  ENV: env.REACT_APP_ENV,
  MUI_LICENSE_KEY: env.REACT_APP_MUI_LICENSE_KEY,
  AUTH_ENDPOINT: env.REACT_APP_AUTH_ENDPOINT,
  API_URL: env.REACT_APP_API_URL,
  USE_CAPTCHA: env.REACT_APP_USE_CAPTCHA || 'No',
 BASE_PATH: env.REACT_APP_BASE_PATH || '/',
  ONESIGNALAPPID: env.REACT_APP_ONESIGNALAPPID,
  IS_SWITCH_THEME: env.REACT_APP_IS_SWITCH_THEME || 'Yes',
  auth: {
    GRANYTYPE: env.REACT_APP_GRANYTYPE || 'password',
    REFRESHGRANTTYPE: env.REACT_APP_REFRESHGRANTTYPE || 'refresh_token',
  },
};
export default ConfigData;