import checkoutFormModel from './checkoutFormModel';

const {
  formField: {
    title,
    categoryType,
    assetCategoryId,
    equipmentCategoryId,
    Priority,
    maintenanceTeamId,
    taskId,
    PPMBy,
    type,
    SchedulerOperationType,
    ScoreType,
    startingDate,
    endDate,
    Duration,
    timePeriod,
    Hourly,
    HourlyConfiguration,
    mo,
    tu,
    we,
    th,
    fr,
    sa,
    su,
    atStart,
    atDone,
    atReview,
    Recurrency,
    interval,
    ruleType,
    monthBy,
    dayBy,
    Day,
    enforceTime,
    nfcScanStart,
    nfcScanDone,
    qrScanStart,
    qrScanDone,
    weekList,
    schedulerType,
  },
} = checkoutFormModel;

export default {
  [title.name]: '',
  [categoryType.name]: { value: 'e', label: 'Equipment' },
  [assetCategoryId.name]: '',
  [equipmentCategoryId.name]: '',
  [Priority.name]: '',
  [maintenanceTeamId.name]: '',
  [taskId.name]: '',
  [PPMBy.name]: '',
  [type.name]: 'multiple',
  [SchedulerOperationType.name]: { value: 'PPM', label: 'PPM' },
  [ScoreType.name]: '',
  [startingDate.name]: '',
  [endDate.name]: '',
  [Duration.name]: 0.00,
  [timePeriod.name]: '',
  [Hourly.name]: '',
  [HourlyConfiguration.name]: '',
  [mo.name]: 0,
  [tu.name]: 0,
  [we.name]: 0,
  [th.name]: 0,
  [fr.name]: 0,
  [sa.name]: 0,
  [su.name]: 0,
  [atStart.name]: 0,
  [atDone.name]: 0,
  [atReview.name]: 0,
  [Recurrency.name]: '',
  [interval.name]: 1,
  [ruleType.name]: '',
  [monthBy.name]: '',
  [dayBy.name]: '',
  [Day.name]: '',
  [weekList.name]: '',
  [enforceTime.name]: 0,
  [nfcScanStart.name]: 0,
  [nfcScanDone.name]: 0,
  [qrScanStart.name]: 0,
  [qrScanDone.name]: 0,
  [schedulerType.name]: { value: 'Inspection Checklist', label: 'Inspection Checklist' },
};
