import checkoutFormModel from './settingsCheckoutFormModel';

const {
  formField: {
    atStart,
    atReview,
    atDone,
    qrScanStart,
    qrScanDone,
    generatePpmAdvance,
    enforceTime,
    nfcScanStart,
    nfcScanDone,
    reviewRequired,
    reviewApproval,
    reviewComment,
    signoffApproval,
    signoffRequired,
    subAssets,
    indirectChild,
    isParent,
    performMissed,
    allowUsers,
    formatType,
    reportReason,
    allowExternalPPM,
    sendExternalPPM,
    sendEmail,
    sendCopyEmail,
    sendVendorEmail,
    externalEmail,
    restrictPPM,
    instructions,
    terms,
    disclaimer,
    isonHoldApproval,
    onHoldMax,
    onHoldApproval,
    onHoldRecipients,
    onHoldRequest,
    onHoldMail,
    onHoldTemplate,
    remainderMail,
    slaMail,
    reasonAccess,
  },
} = checkoutFormModel;

export default {
  [atStart.name]: '',
  [atReview.name]: '',
  [atDone.name]: '',
  [qrScanStart.name]: '',
  [qrScanDone.name]: '',
  [generatePpmAdvance.name]: '',
  [enforceTime.name]: '',
  [nfcScanStart.name]: '',
  [nfcScanDone.name]: '',
  [reviewRequired.name]: '',
  [reviewApproval.name]: '',
  [reviewComment.name]: '',
  [signoffApproval.name]: '',
  [signoffRequired.name]: '',
  [subAssets.name]: '',
  [indirectChild.name]: '',
  [isParent.name]: '',
  [performMissed.name]: '',
  [allowUsers.name]: '',
  [formatType.name]: '',
  [reportReason.name]: '',
  [allowExternalPPM.name]: '',
  [sendExternalPPM.name]: '',
  [sendEmail.name]: '',
  [sendCopyEmail.name]: '',
  [sendVendorEmail.name]: '',
  [externalEmail.name]: '',
  [restrictPPM.name]: '',
  [instructions.name]: '',
  [terms.name]: '',
  [disclaimer.name]: '',
  [isonHoldApproval.name]: '',
  [onHoldMax.name]: '',
  [onHoldApproval.name]: '',
  [onHoldRecipients.name]: '',
  [onHoldRequest.name]: '',
  [onHoldMail.name]: '',
  [onHoldTemplate.name]: '',
  [remainderMail.name]: '',
  [slaMail.name]: '',
  [reasonAccess.name]: '',
};
