import checkoutFormModel from './settingsCheckoutFormModel';

const {
  formField: {
    atStart,
    atReview,
    atDone,
    isAutomaticConfirm,
    qrScanStart,
    qrScanDone,
    nfcScanStart,
    nfcScanDone,
    resourceCalendarId,
    isPhotoMandatory,
    qrCodeImage,
    submitGloballyInApp,
    isSmartloggerScan,
    autoSyncIntervalMobile,
    osAppId,
    osUrl,
    hasAuditModeQr,
    hasAuditModeNfc,
    hasAuditModeRfid,
    hasAuditModeManual,
    isGenerateOneWo,
    osAppKey,
    responseValue,
    hspaceAppKey,
    hsenseAppUrl,
    hsenseSupportEmail,
    hspaceWebsiteUrl,
  },
} = checkoutFormModel;

export default {
  [atStart.name]: '',
  [atReview.name]: '',
  [atDone.name]: '',
  [isAutomaticConfirm.name]: '',
  [qrScanStart.name]: '',
  [qrScanDone.name]: '',
  [nfcScanStart.name]: '',
  [nfcScanDone.name]: '',
  [resourceCalendarId.name]: '',
  [isPhotoMandatory.name]: '',
  [qrCodeImage.name]: '',
  [submitGloballyInApp.name]: '',
  [isSmartloggerScan.name]: '',
  [autoSyncIntervalMobile.name]: '',
  [osAppId.name]: '',
  [osUrl.name]: '',
  [hasAuditModeQr.name]: '',
  [hasAuditModeNfc.name]: '',
  [hasAuditModeRfid.name]: '',
  [hasAuditModeManual.name]: '',
  [isGenerateOneWo.name]: '',
  [osAppKey.name]: '',
  [responseValue.name]: '',
  [hspaceAppKey.name]: '',
  [hsenseAppUrl.name]: '',
  [hsenseSupportEmail.name]: '',
  [hspaceWebsiteUrl.name]: '',
};
