import checkoutFormModel from './checkoutFormModel';

const {
  formField: {
    visitFor,
    refName,
    visitorType,
    nameValue,
    visitorPhoto,
    mobile,
    email,
    organization,
    idProof,
    documentProof,
    employeeId,
    employeePhoto,
    employeeMobile,
    employeeEmail,
    hostName,
    hostEmail,
    hostCompany,
    plannedIn,
    plannedOut,
    spaceId,
    actualIn,
    actualOut,
    purpose,
    entryStatus,
    allowMultipleEntry,
    tenantId,
  },
} = checkoutFormModel;

export default {
  [refName.name]: 'New',
  [visitFor.name]: 'OTHER',
  [visitorType.name]: '',
  [nameValue.name]: '',
  [visitorPhoto.name]: '',
  [mobile.name]: '',
  [email.name]: '',
  [organization.name]: '',
  [idProof.name]: '',
  [documentProof.name]: '',
  [employeeId.name]: '',
  [employeePhoto.name]: '',
  [employeeMobile.name]: '',
  [employeeEmail.name]: '',
  [hostName.name]: '',
  [hostEmail.name]: '',
  [hostCompany.name]: '',
  [plannedIn.name]: '',
  [plannedOut.name]: '',
  [spaceId.name]: '',
  // [actualIn.name]: '',
  // [actualOut.name]: '',
  [purpose.name]: '',
  // [entryStatus.name]: '',
  [allowMultipleEntry.name]: false,
  [tenantId.name]: '',
};
