import checkoutFormModel from './settingsCheckoutFormModel';

const {
  formField: {
    // hasSiteSpecificCategory,
    isEnableItTicket,
    isAutoWo,
    attachmentLimit,
    sendEscalation,
    sendReminder,
    helpdeskFeedback,
    helpdeskSurvey,
    buttonText,
    helpdeskEmail,
    expiryDays,
    feedbackTicket,
    emailFeedback,
    enableExternalHelpdesk,
    uuidValue,
    externalUrl,
    verificationOtp,
    reviewerName,
    reviewerEmail,
    reviewerMobile,
    attachment,
    workLocation,
    mobileVisibility,
    problemCatSubCat,
    shareMailTemplate,
    isVendorField,
    vendorAccessType,
    isAge,
    isConstraints,
    isCost,
  },
} = checkoutFormModel;

export default {
  // [hasSiteSpecificCategory.name]: '',
  [isEnableItTicket.name]: '',
  [isAutoWo.name]: '',
  [attachmentLimit.name]: '',
  [sendEscalation.name]: '',
  [sendReminder.name]: '',
  [helpdeskFeedback.name]: '',
  [helpdeskSurvey.name]: '',
  [buttonText.name]: '',
  [helpdeskEmail.name]: '',
  [expiryDays.name]: '',
  [feedbackTicket.name]: '',
  [emailFeedback.name]: '',
  [enableExternalHelpdesk.name]: '',
  [uuidValue.name]: '',
  [externalUrl.name]: '',
  [verificationOtp.name]: '',
  [reviewerName.name]: '',
  [reviewerEmail.name]: '',
  [reviewerMobile.name]: '',
  [attachment.name]: '',
  [workLocation.name]: '',
  [mobileVisibility.name]: '',
  [problemCatSubCat.name]: '',
  [shareMailTemplate.name]: '',
  [isVendorField.name]: '',
  [vendorAccessType.name]: '',
  [isAge.name]: '',
  [isConstraints.name]: '',
  [isCost.name]: '',
};
