import checkoutFormModel from './checkoutFormModel';

const {
  formField: {
    company,
    personName,
    Mobile,
    Email,
    Channel,
    issueType,
    subject,
    categoryId,
    subCategorId,
    priority,
    parentId,
    Description,
    typeCategory,
    maintenanceTeamId,
    assetId,
    equipmentId,
    raisedBy,
    incidentTypeId,
    incidentSeverityId,
    incidentState,
    vendorId,
    Constraints,
    Cost,
    ticketType,
    tenantName,
    tenantId,
  },
} = checkoutFormModel;

export default {
  [company.name]: '',
  [personName.name]: '',
  [Mobile.name]: '',
  [Email.name]: '',
  [Channel.name]: '',
  [issueType.name]: '',
  [subject.name]: '',
  [categoryId.name]: '',
  [subCategorId.name]: '',
  [priority.name]: '',
  [parentId.name]: '',
  [Description.name]: '',
  [typeCategory.name]: 'equipment',
  [maintenanceTeamId.name]: '',
  [equipmentId.name]: '',
  [assetId.name]: '',
  [raisedBy.name]: 'self',
  [incidentTypeId.name]: '',
  [incidentSeverityId.name]: '',
  [incidentState.name]: '',
  [vendorId.name]: '',
  [Constraints.name]: '',
  [Cost.name]: '0.00',
  [ticketType.name]: 'Proactive',
  [tenantName.name]: '',
  [tenantId.name]: '',
};
