import checkoutFormModel from './checkoutFormModel';

const {
  formField: {
    raisedBy,
    raisedOn,
    title,
    incidentDate,
    serviceCategoryId,
    descriptionOfBreakdown,
    resultsInStatutoryNonCompliance,
    isServiceImpacted,
    serviceImpactedIds,
    incidentAge,
    attendedOn,
    actionTaken,
    closedOn,
    remark,
    companyId,
    types,
    spaceId,
    equipmentId,
    ciriticalitys,
    amcStatus,
    vendorName,
    complaintNo,
    vendorSrNumber,
    Priority,
  },
} = checkoutFormModel;

export default {
  [raisedBy.name]: '',
  [raisedOn.name]: '',
  [title.name]: '',
  [incidentDate.name]: '',
  [serviceCategoryId.name]: '',
  [descriptionOfBreakdown.name]: '',
  [resultsInStatutoryNonCompliance.name]: '',
  [ciriticalitys.name]: '',
  [isServiceImpacted.name]: '',
  [serviceImpactedIds.name]: '',
  [incidentAge.name]: '02.07',
  [attendedOn.name]: '',
  [actionTaken.name]: '',
  [closedOn.name]: '',
  [remark.name]: '',
  [companyId.name]: '',
  [types.name]: 'Space',
  [spaceId.name]: '',
  [equipmentId.name]: '',
  [amcStatus.name]: '',
  [vendorName.name]: '',
  [complaintNo.name]: '',
  [vendorSrNumber.name]: '',
  [Priority.name]: '',
};
