import userFormModel from './userFormModel';

const {
  formField: {
    name,
    email,
    companyId,
    roleIds,
    employee,
    shiftId,
    departmentId,
    biometricId,
    employeeId,
    vendorId,
    companyIds,
    mobileUser,
    associateId,
    phoneNumber,
    associateTo,
    Password,
    isTempPassword,
    isSOWEmployee,
    defaultUserRole,
    Designation,
    teamIds,
  },
} = userFormModel;

export default {
  [name.name]: '',
  [email.name]: '',
  [companyId.name]: '',
  [roleIds.name]: '',
  [employee.name]: 'yes',
  [shiftId.name]: '',
  [departmentId.name]: '',
  [biometricId.name]: '',
  [employeeId.name]: '',
  [vendorId.name]: '',
  [companyIds.name]: '',
  [mobileUser.name]: 'no',
  [associateId.name]: '',
  [phoneNumber.name]: '',
  [associateTo.name]: 'Client',
  [Password.name]: '',
  [isTempPassword.name]: '',
  [isSOWEmployee.name]: '',
  [defaultUserRole.name]: '',
  [Designation.name]: '',
  [teamIds.name]: '',
};
