export const sideNavList = [
  {
    name: "HOME",
    displayName: "Home",
    path: "/",
    pathString: "",
    itemName: "Home",
    modulePath: "/",
  },
  {
    name: "HELPDESK",
    displayName: "Helpdesk",
    path: "/helpdesk-insights-overview",
    pathString: "helpdesk",
    itemName: "Helpdesk",
    modulePath: "/helpdesk",
  },
  {
    name: "ESG",
    displayName: "ESG",
    path: "/esg-environmental",
    pathString: "environmental",
    itemName: "ESG",
    modulePath: "/esg",
  },
  {
    name: "Occupancy",
    displayName: "Occupancy",
    path: "/occupancy",
    pathString: "occupancy",
    itemName: "Occupancy",
    modulePath: "/occupancy",
  },
  {
    name: "ASSETS",
    displayName: "Assets",
    path: "/asset-overview",
    pathString: "asset",
    itemName: "Asset Registry",
    modulePath: "/asset-registry",
  },
  {
    name: "WORK ORDERS",
    displayName: "Work Orders",
    path: "/workorders-overview",
    pathString: "workorders",
    itemName: "Work Orders",
    modulePath: "/work-orders",
  },
  {
    name: "INCIDENT",
    displayName: "Incident",
    path: "/incident-overview",
    pathString: "incident",
    itemName: "Incident Management",
    modulePath: "/incident-mangement",
  },
  {
    name: "INVENTORY",
    displayName: "Inventory",
    path: "/inventory-overview",
    pathString: "inventory",
    itemName: "Inventory",
    modulePath: "/inventory",
  },
  {
    name: "BUILDING COMPLIANCE",
    displayName: "Building Compliance",
    path: "/buildingcompliance-overview",
    pathString: "building",
    itemName: "Building Compliance",
    modulePath: "/building-compliance",
  },
  {
    name: "VISITOR MANAGEMENT",
    displayName: "Visitor Management",
    path: "/visitormanagement-overview",
    pathString: "visitormanagement",
    itemName: "Visitor Management",
    modulePath: "/visitor-management",
  },
  {
    name: "ANALYTICS",
    displayName: "Analytics",
    path: "/analytics",
    pathString: "analytics",
    itemName: "Analytics",
    modulePath: "/analytics",
  },
  {
    name: "NOC Dashboard",
    displayName: "NOC Dashboards",
    path: "/noc/engineering",
    pathString: "noc",
    itemName: "NOC Dashboard",
    modulePath: "/noc-dashboard",
  },
  {
    name: "SPACE MANAGEMENT",
    displayName: "Space Management",
    path: "/spaceManagement-overview",
    pathString: "space-management",
    itemName: "HSpace - Space Management",
    modulePath: "/space-management",
  },
  {
    name: "52 WEEK PPM",
    displayName: "52 Week PPM",
    path: "/preventive-overview",
    pathString: "preventive",
    itemName: "52 Week PPM",
    modulePath: "/preventive-maintenance",
  },
  {
    name: "INSPECTION MAINTENANCE",
    displayName: "Inspection Schedule",
    path: "/inspection-overview",
    pathString: "inspection",
    itemName: "Inspection Schedule",
    modulePath: "/inspection-maintenance",
  },
  {
    name: "PURCHASE",
    displayName: "Purchase",
    path: "/purchase/requestforquotation",
    pathString: "purchase",
    itemName: "Purchase",
    modulePath: "/purchase",
  },
  {
    name: "PANTRY MANAGEMENT",
    displayName: "Pantry Management",
    path: "/pantry-overview",
    pathString: "pantry",
    itemName: "Pantry Management",
    modulePath: "/pantry-management",
  },
  {
    name: "SURVEY",
    displayName: "Survey",
    path: "/survey-overview",
    pathString: "survey",
    itemName: "Survey",
    modulePath: "/survey",
  },
  {
    name: "HR SETTINGS",
    displayName: "HR Settings",
    path: "/hr/employees",
    pathString: "employees",
    itemName: "HR Settings",
    modulePath: "/hr-settings",
  },
  {
    name: "MAILROOM",
    displayName: "Mail Room Management",
    path: "/mailroom-overview",
    pathString: "mailroom",
    itemName: "Mail Room Management",
    modulePath: "/mailroomm",
  },
  {
    name: "COMMODITYTRANSACTIONS",
    displayName: "Commodity Transactions",
    path: "/commodity-overview",
    pathString: "commodity",
    itemName: "Commodity Transactions",
    modulePath: "/commodity-transactions",
  },
  {
    name: "IT ASSET MANAGEMENT",
    displayName: "IT Asset Management",
    path: "/itasset-overview",
    pathString: "ita",
    itemName: "IT Asset Management",
    modulePath: "/it-asset-management",
  },
  {
    name: "WORKPERMIT",
    displayName: "Work Permit",
    path: "/workpermit-overview",
    pathString: "workpermit",
    itemName: "Work Permit",
    modulePath: "/workpermit",
  },
  {
    name: "GATEPASS",
    displayName: "Gate Pass",
    path: "/gatepass-overview",
    pathString: "gatepass",
    itemName: "Gate Pass",
    modulePath: "/gatepass",
  },
  {
    name: "CONFIGURATION",
    displayName: "Configuration",
    path: "/configuration/overview",
    pathString: "configuration",
    itemName: "Configuration",
    modulePath: "/configuration",
  },
  {
    name: "BREAKDOWNTRACKER",
    displayName: "Breakdown Tracker",
    path: "/breakdown-overview",
    pathString: "breakdown",
    itemName: "Breakdown Tracker",
    modulePath: "/breakdowntracker",
  },
  {
    name: "AUDITSYSTEM",
    displayName: "Audit System",
    path: "/audit-overview",
    pathString: "audit",
    itemName: "Audit System",
    modulePath: "/auditsystem",
  },
  {
    name: "ADMIN SETUP",
    displayName: "Admin Setup",
    "path": "/siteadmin-overview",
    "pathString": "-siteadmin",
    itemName: "Admin Setup",
    modulePath: "/admin-setup",
  },
  {
    name: "IOT SYSTEM",
    displayName: "IOT System",
    path: "http://ec2-3-121-188-84.eu-central-1.compute.amazonaws.com:9001/",
    itemName: "IOT System",
    modulePath: "/iot-setup",
  },
  {
    name: "ENERGY MANAGEMENT",
    displayName: "Energy Management",
    path: "http://52.66.109.243:8080/dashboard/011054f0-dbe6-11ea-b3d8-67574b317d9f?publicId=32f81850-ec20-11ea-b3d8-67574b317d9f",
    itemName: "Energy Management",
    modulePath: "/energy-management",
  },
  {
    name: "SMART WASHROOM",
    displayName: "Smart Washroom",
    path: "/smart-clean",
    pathString: "smart-clean",
    itemName: "Smart Washroom",
    modulePath: "/smart-washroom",
  },
  {
    name: "IAQ DASHBOARD",
    displayName: "IAQ",
    path: "/iaq-dashboard",
    pathString: "iaq-dashboard",
    itemName: "IAQ Dashboard",
    modulePath: "/iaq",
  },
  // {
  //   name: "UPS DASHBOARDS",
  //   displayName: "UPS Dashboards",
  //   path: "/ups-summary-overview",
  //   pathString: "ups",
  //   itemName: "UPS",
  // },
  {
    name: "AIRQUALITY",
    displayName: "Air Quality Monitoring",
    path: "/airquality-overview",
    pathString: "airquality",
    itemName: "Air Quality Monitoring",
    modulePath: "/airquality",
  },
  {
    name: "Attendance Logs",
    displayName: "Attendance Logs",
    path: "/attendance-overview",
    pathString: "attendance-overview",
    itemName: "Attendance Logs",
    modulePath: "/attendance-logs",
  },
  {
    name: "Energy",
    displayName: "Energy",
    path: "/energy-insights-overview",
    pathString: "energy",
    itemName: "Energy",
    modulePath: "/energy",
  },
  {
    name: "Restrooms",
    displayName: "Restrooms",
    path: "/restrooms-insights-overview",
    pathString: "restrooms",
    itemName: "Restrooms",
  },
  {
    name: "UPS",
    displayName: "UPS",
    path: "/ups-summary-overview",
    pathString: "ups",
    itemName: "UPS",
  },
  {
    name: "Users",
    displayName: "Users",
    path: "/team-members",
    pathString: "teams",
    itemName: "Users",
  },
  {
    name: "SLA-KPI Audit",
    displayName: "SLA-KPI Audit",
    path: "/sla-audit-overview",
    pathString: "sla-",
    itemName: "SLA-KPI Audit",
  },
  {
    name: "Consumption Tracker",
    displayName: "Consumption Tracker",
    path: "/consumption-tracker-overview",
    pathString: "-tracker",
    itemName: "Consumption Tracker",
  },
  {
    name: "FIT Tracker",
    displayName: "FIT Tracker",
    path: "/fitTracker-overview",
    pathString: "fit",
    itemName: "FIT Tracker",
  },
  {
    name: "HX Incident Report",
    displayName: "HX Incident Report",
    path: "/hx-incident-overview",
    pathString: "hx-",
    itemName: "HX Incident Report",
  },
  {
    name: "WASTE TRACKER",
    displayName: "Waste Tracker",
    path: "/waste-overview",
    pathString: "waste",
    itemName: "Waste Tracker",
    modulePath: "/waste-overview",
  },
  {
    name: "CXO ANALYTICS",
    displayName: "CXO Analytics",
    path: "/cxo-summary",
    pathString: "cxo",
    itemName: "CXO Analytics",
    modulePath: "/cxo-summary",
  },
  {
    name: "HAZARDS",
    displayName: "Hazards",
    path: "/hazard-overview",
    pathString: "hazard",
    itemName: "Hazards",
    modulePath: "/hazard-overview",
  },
  {
    name: "BMS ALARMS",
    displayName: "BMS Alarms",
    path: "/bms-alarms-overview",
    pathString: "bms",
    itemName: "BMS Alarms",
    modulePath: "/bms-alarms-overview",
  },
  {
    name: "Audit Management",
    displayName: "Audit Management",
    path: "/audit-management-overview",
    pathString: "amanage",
    itemName: "Audit Management",
    modulePath: "/audit-management-overview",
  },
];
