import checkoutFormModel from './checkoutFormModel';

const {
  formField: {
    companyType,
    name,
    address,
    city,
    stateId,
    countryId,
    zip,
    phone,
    mobile,
    email,
    website,
    Lang,
    categoryId,
    customer,
    supplier,
    isVisitor,
    isTenant,
    isFmServices,
    isCommandCentre,
    filePath,
    isManPowerAgency,
    internalReference,
    barcode,
    companyId,
    userId,
    propertyPaymentTermId,
    propertySupplierPaymentTermId,
    websiteId,
    propertyAccountPositionId,
    dedicatedSupportUserId,
    slaId,
    propertyAccountReceivableId,
    propertyAccountPayableId,
    comment,
    companyName,
    imageMedium,
    imageSmall,
    bankIds,
  },
} = checkoutFormModel;

export default {
  [companyType.name]: 'company',
  [name.name]: '',
  [categoryId.name]: '',
  [address.name]: '',
  [city.name]: '',
  [stateId.name]: '',
  [countryId.name]: '',
  [zip.name]: '',
  [phone.name]: '',
  [mobile.name]: '',
  [email.name]: '',
  [website.name]: '',
  [Lang.name]: '',
  [customer.name]: true,
  [supplier.name]: true,
  [isVisitor.name]: true,
  [isTenant.name]: true,
  [isFmServices.name]: true,
  [isCommandCentre.name]: true,
  [filePath.name]: '',
  [isManPowerAgency.name]: true,
  [internalReference.name]: '',
  [barcode.name]: '',
  [companyId.name]: '',
  [userId.name]: '',
  [propertyPaymentTermId.name]: '',
  [propertySupplierPaymentTermId.name]: '',
  [websiteId.name]: '',
  [propertyAccountPositionId.name]: '',
  [dedicatedSupportUserId.name]: '',
  [slaId.name]: '',
  [propertyAccountReceivableId.name]: '',
  [propertyAccountPayableId.name]: '',
  [comment.name]: '',
  [companyName.name]: '',
  [imageMedium.name]: false,
  [imageSmall.name]: false,
  [bankIds.name]: '',
};
