import checkoutFormModel from './checkoutFormModel';

const {
  formField: {
    groupId,
    type,
    equipmentId,
    spaceId,
    company,
    maintenanceTeamId,
    taskId,
    checklistId,
    startsAt,
    durationAt,
    excludeHolidays,
    parentSchedule,
    priorityValue,
    commencesOn,
    endsOn,
    descriptionValue,
    remindBefore,
    missedAlert,
    recipients,
    mo,
    tu,
    we,
    th,
    fr,
    sa,
    su,
    atStart,
    atDone,
    atReview,
    enforceTime,
    qrScanStart,
    qrScanDone,
    nfcScanStart,
    nfcScanDone,
  },
} = checkoutFormModel;

export default {
  [groupId.name]: '',
  [type.name]: { value: 'Equipment', label: 'Equipment' },
  [equipmentId.name]: '',
  [spaceId.name]: '',
  [company.name]: '',
  [maintenanceTeamId.name]: '',
  [taskId.name]: '',
  [checklistId.name]: '',
  [startsAt.name]: '',
  [durationAt.name]: '',
  [excludeHolidays.name]: '',
  [parentSchedule.name]: '',
  [priorityValue.name]: { value: '1', label: 'Normal' },
  [commencesOn.name]: '',
  [endsOn.name]: '',
  [descriptionValue.name]: '',
  [remindBefore.name]: '0.00',
  [missedAlert.name]: '',
  [recipients.name]: '',
  [mo.name]: 0,
  [tu.name]: 0,
  [we.name]: 0,
  [th.name]: 0,
  [fr.name]: 0,
  [sa.name]: 0,
  [su.name]: 0,
  [atStart.name]: 0,
  [atDone.name]: 0,
  [atReview.name]: 0,
  [enforceTime.name]: true,
  [qrScanStart.name]: 0,
  [qrScanDone.name]: 0,
  [nfcScanStart.name]: 0,
  [nfcScanDone.name]: 0,
};
