import checkoutFormModel from './checkoutFormModel';

const {
  formField: {
    productName,
    categoryId,
    productType,
    sales,
    purchase,
    maintenance,
    interanalReference,
    barcodeId,
    routes,
    salesprice,
    cost,
    volumeId,
    weightId,
    specificationValue,
    brandValue,
    department,
    reorderLevel,
    alertLevel,
    reorderQuantity,
    perferredValue,
    uniqueCode,
  },
} = checkoutFormModel;

export default {
  [productName.name]: '',
  [categoryId.name]: '',
  [productType.name]: '',
  [sales.name]: false,
  [purchase.name]: true,
  [maintenance.name]: true,
  [interanalReference.name]: '',
  [uniqueCode.name]: '',
  [barcodeId.name]: '',
  [routes.name]: [],
  [salesprice.name]: 1.00,
  [cost.name]: 0.00,
  [weightId.name]: 0.00,
  [volumeId.name]: 0.00,
  [specificationValue.name]: '',
  [brandValue.name]: '',
  [department.name]: '',
  [reorderLevel.name]: 0.00,
  [alertLevel.name]: 0.00,
  [reorderQuantity.name]: 0.00,
  [perferredValue.name]: '',
};
