import * as Yup from 'yup';
import checkoutFormModel from './checkoutFormModel';

const {
  formField: {
    title,
    description,
    pageTitle,
    questionType,
    validationErrorMsg,
    commentsMessage,
    errorMessage,
    categoryType,
    spaceId,
    equipmentCategoryId,
    verificationByOtp,
    reviewerName,
    reviewerEmail,
    reviewerMobile,
    disclaimer,
    disclaimerText,
    feedbackText,
    surveyTime,
    validateMinFloat,
    validateMaxFloat,
    isAllSpaces,
    spaceLevel,
    hasTenant,
    isSendEmail,
    isRepeats,
    startsOn,
    Day,
    recurrentRule,
    deadLine,
    answeredAlready,
    deadlineElapsed,
    escalationPolicyId,
    campaignEmailId,
    reminderEmailId,
    mo,
    tu,
    we,
    th,
    fr,
    sa,
    su,
  },
} = checkoutFormModel;

export default {
  [title.name]: '',
  [description.name]: '',
  [pageTitle.name]: '',
  [validationErrorMsg.name]: 'The answer you entered has an invalid format.',
  [commentsMessage.name]: 'If other, please specify:',
  [errorMessage.name]: 'This question requires an answer.',
  [questionType.name]: 'textbox',
  [categoryType.name]: '',
  [verificationByOtp.name]: '',
  [reviewerName.name]: 'Required',
  [reviewerEmail.name]: 'Required',
  [reviewerMobile.name]: 'Required',
  [hasTenant.name]: 'Optional',
  [disclaimer.name]: 'Required',
  [disclaimerText.name]: '',
  [feedbackText.name]: 'Thank you text | Thank you for your feedback.',
  [surveyTime.name]: '',
  [validateMinFloat.name]: '0.00',
  [validateMaxFloat.name]: '0.00',
  [isAllSpaces.name]: false,
  [spaceLevel.name]: '',
  [isSendEmail.name]: false,
  [isRepeats.name]: true,
  [startsOn.name]: new Date(),
  [Day.name]: 1,
  [mo.name]: 0,
  [tu.name]: 0,
  [we.name]: 0,
  [th.name]: 0,
  [fr.name]: 0,
  [sa.name]: 0,
  [su.name]: 0,
  [recurrentRule.name]: '',
  [deadLine.name]: 1,
  [answeredAlready.name]: 'Thank you. You have responded already.',
  [deadlineElapsed.name]: 'Oops! This survey has expired.',
  [escalationPolicyId.name]: false,
  [campaignEmailId.name]: false,
  [reminderEmailId.name]: false,
  [equipmentCategoryId.name]: Yup.string().when('category_type', {
    is: 'e',
    then: Yup.string().required('Equipment is required'),
  }),
  [spaceId.name]: Yup.string().when('category_type', {
    is: 'ah',
    then: Yup.string().required('Space is required'),
  }),
};
