import checkoutFormModel from './checkoutFormModel';

const {
  formField: {
    questionTitle,
    questionType,
    questionGroup,
    smartLogger,
    mandatoryAnswer,
    mandatoryPhoto,
    expected,
    multipleLine,
    errorMessage,
    validateEntry,
    expectedMax,
    expectedMin,
    expectedType,
    commentsField,
    hasAttachment,
    inspectionMethod,
    requiresAction,
    feedback,
    requiresVerification,
    preventiveAction,
    correctiveAction,
    isResolution,
    enableCondition,
    conditionQuestion,
    optionId,
  },
} = checkoutFormModel;

export default {
  [questionTitle.name]: '',
  [questionType.name]: '',
  [questionGroup.name]: '',
  [smartLogger.name]: '',
  [mandatoryAnswer.name]: '',
  [mandatoryPhoto.name]: '',
  [expected.name]: '',
  [multipleLine.name]: '',
  [errorMessage.name]: 'This question requires an answer.',
  [validateEntry.name]: '',
  [expectedMax.name]: 0,
  [expectedMin.name]: 0,
  [expectedType.name]: '',
  [commentsField.name]: '',
  [hasAttachment.name]: '',
  [inspectionMethod.name]: '',
  [requiresAction.name]: '',
  [feedback.name]: '',
  [requiresVerification.name]: '',
  [preventiveAction.name]: '',
  [correctiveAction.name]: '',
  [isResolution.name]: '',
  [enableCondition.name]: '',
  [conditionQuestion.name]: '',
  [optionId.name]: '',
};
